/* eslint-disable no-console */
import { readdir, readFile } from "node:fs/promises";
import path from "node:path";

type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

type RouteCase = {
  method: HttpMethod;
  routeFile: string;
  pathTemplate: string;
  requestPath: string;
};

type CaseRunResult = {
  ok: boolean;
  status: number | null;
  durationMs: number;
  message: string;
};

const EXCLUDED_ROUTE_PATHS = new Set<string>(["/api/auth/google", "/api/auth/google/callback"]);

const API_DIR = path.join(process.cwd(), "src", "app", "api");
const BASE_URL = process.env.API_BASE_URL ?? "http://localhost:3000";
const STRICT = process.env.STRICT_API_TEST === "1";
const TIMEOUT_MS = Number(process.env.API_TEST_TIMEOUT_MS ?? "15000");
const PERF_COMPARE = process.env.API_PERF_COMPARE === "1";
const PERF_CONCURRENCY = Number(process.env.API_PERF_CONCURRENCY ?? "5");
const PERF_VALIDATION_PERCENT = Number(process.env.PERF_VALIDATION_PERCENT ?? "5");

const DEFAULT_TEST_EMAIL =
  process.env.TEST_EMAIL ??
  `api-test-${Date.now()}-${Math.floor(Math.random() * 10000)}@example.com`;
const DEFAULT_TEST_PASSWORD = process.env.TEST_PASSWORD ?? "Passw0rd!123";
const DEFAULT_TEST_NAME = process.env.TEST_NAME ?? "API Test User";

const methodRegex = /export\s+async\s+function\s+(GET|POST|PUT|PATCH|DELETE)\s*\(/g;

function toEnvKey(param: string): string {
  return param
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/-/g, "_")
    .toUpperCase();
}

function resolveDynamicSegments(pathTemplate: string): string {
  return pathTemplate.replace(/\[([^\]]+)\]/g, (_full, rawParam: string) => {
    const param = String(rawParam);
    const envKey = toEnvKey(param);
    return process.env[envKey] ?? `test-${param.toLowerCase()}`;
  });
}

function buildBody(routePath: string, method: HttpMethod): unknown {
  if (method === "GET" || method === "DELETE") return undefined;

  if (routePath === "/api/auth/signup") {
    return {
      name: DEFAULT_TEST_NAME,
      email: DEFAULT_TEST_EMAIL,
      password: DEFAULT_TEST_PASSWORD,
    };
  }

  if (routePath === "/api/auth/signin") {
    return {
      email: process.env.SIGNIN_EMAIL ?? DEFAULT_TEST_EMAIL,
      password: process.env.SIGNIN_PASSWORD ?? DEFAULT_TEST_PASSWORD,
    };
  }

  if (routePath.includes("/accept")) {
    return {};
  }

  return {
    name: "API smoke test payload",
    title: "API smoke test payload",
    description: "Generated by scripts/api-smoke-test.ts",
  };
}

async function walkRouteFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        return walkRouteFiles(fullPath);
      }
      if (entry.isFile() && entry.name === "route.ts") {
        return [fullPath];
      }
      return [];
    })
  );
  return files.flat();
}

async function discoverRouteCases(): Promise<RouteCase[]> {
  const routeFiles = await walkRouteFiles(API_DIR);
  const routeCases: RouteCase[] = [];

  for (const routeFile of routeFiles) {
    const source = await readFile(routeFile, "utf8");
    const matches = Array.from(source.matchAll(methodRegex));
    if (!matches.length) continue;

    const routeFragment = routeFile
      .replace(API_DIR, "")
      .replace(/\\/g, "/")
      .replace(/\/route\.ts$/, "");
    const pathTemplate = `/api${routeFragment === "" ? "" : routeFragment}`;
    const requestPath = resolveDynamicSegments(pathTemplate);

    for (const match of matches) {
      const method = match[1] as HttpMethod;
      if (EXCLUDED_ROUTE_PATHS.has(pathTemplate)) {
        continue;
      }
      routeCases.push({ method, routeFile, pathTemplate, requestPath });
    }
  }

  routeCases.sort((a, b) => {
    if (a.requestPath === b.requestPath) return a.method.localeCompare(b.method);
    return a.requestPath.localeCompare(b.requestPath);
  });

  return routeCases;
}

function getCookieHeader(): string | null {
  const cookiePairs: string[] = [];
  if (process.env.ACCESS_TOKEN) {
    cookiePairs.push(`accessToken=${process.env.ACCESS_TOKEN}`);
  }
  if (process.env.REFRESH_TOKEN) {
    cookiePairs.push(`refreshToken=${process.env.REFRESH_TOKEN}`);
  }
  if (process.env.COOKIE_HEADER) {
    cookiePairs.push(process.env.COOKIE_HEADER);
  }
  return cookiePairs.length ? cookiePairs.join("; ") : null;
}

function getExpectedStatusesInStrictMode(testCase: RouteCase): number[] {
  const key = `${testCase.method} ${testCase.pathTemplate}`;
  const expectedByRoute: Record<string, number[]> = {
    "GET /api/auth/google/callback": [200, 302, 400],
    "GET /api/auth/me": [200, 401],
    "POST /api/auth/refresh": [200, 401],
    "POST /api/auth/signin": [200, 401, 429],
  };
  return expectedByRoute[key] ?? [200, 201, 202, 204, 301, 302, 303, 307, 308];
}

async function runSingleCase(testCase: RouteCase): Promise<CaseRunResult> {
  const url = `${BASE_URL}${testCase.requestPath}`;
  const body = buildBody(testCase.pathTemplate, testCase.method);
  const cookieHeader = getCookieHeader();
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), TIMEOUT_MS);
  const start = performance.now();

  try {
    const response = await fetch(url, {
      method: testCase.method,
      headers: {
        "content-type": "application/json",
        ...(cookieHeader ? { cookie: cookieHeader } : {}),
      },
      body: body === undefined ? undefined : JSON.stringify(body),
      signal: controller.signal,
    });

    clearTimeout(timeout);
    const strictExpectedStatuses = getExpectedStatusesInStrictMode(testCase);
    const ok = STRICT
      ? strictExpectedStatuses.includes(response.status) ||
        (response.status === 429 && testCase.pathTemplate.startsWith("/api/auth/"))
      : response.status < 500;
    const durationMs = performance.now() - start;
    const message = ok
      ? STRICT
        ? `status ${response.status} (expected)`
        : `status ${response.status}`
      : `status ${response.status} (server error or strict failure)`;
    return { ok, status: response.status, durationMs, message };
  } catch (error) {
    clearTimeout(timeout);
    const message = error instanceof Error ? error.message : String(error);
    return { ok: false, status: null, durationMs: performance.now() - start, message };
  }
}

function formatMs(ms: number): string {
  return `${ms.toFixed(2)}ms`;
}

function printBenchmarkSummary(label: string, times: number[]): { totalMs: number; avgMs: number } {
  const totalMs = times.reduce((sum, time) => sum + time, 0);
  const avgMs = times.length ? totalMs / times.length : 0;
  console.log(
    `${label} total: ${formatMs(totalMs)} | avg: ${formatMs(avgMs)} | calls: ${times.length}`
  );
  return { totalMs, avgMs };
}

async function runPerformanceComparison(routeCases: RouteCase[]): Promise<void> {
  console.log("Performance comparison mode enabled.");
  console.log(`Validation target improvement: >= ${PERF_VALIDATION_PERCENT}%`);
  console.log(`Concurrent workers: ${PERF_CONCURRENCY}`);
  console.log("");

  const sequentialTimes: number[] = [];
  const sequentialStart = performance.now();
  for (const testCase of routeCases) {
    const result = await runSingleCase(testCase);
    sequentialTimes.push(result.durationMs);
  }
  const sequentialWallMs = performance.now() - sequentialStart;

  const concurrentTimes: number[] = [];
  const concurrentStart = performance.now();
  let index = 0;
  const workerCount = Math.max(1, PERF_CONCURRENCY);
  const workers = Array.from({ length: workerCount }, async () => {
    while (index < routeCases.length) {
      const currentIndex = index;
      index += 1;
      const result = await runSingleCase(routeCases[currentIndex]);
      concurrentTimes.push(result.durationMs);
    }
  });
  await Promise.all(workers);
  const concurrentWallMs = performance.now() - concurrentStart;

  printBenchmarkSummary("Sequential request latency", sequentialTimes);
  printBenchmarkSummary("Concurrent request latency", concurrentTimes);
  console.log(
    `Sequential wall-clock: ${formatMs(sequentialWallMs)} | Concurrent wall-clock: ${formatMs(
      concurrentWallMs
    )}`
  );
  const improvementPercent =
    sequentialWallMs > 0 ? ((sequentialWallMs - concurrentWallMs) / sequentialWallMs) * 100 : 0;
  const validationPassed = improvementPercent >= PERF_VALIDATION_PERCENT;
  console.log(
    `Improvement: ${improvementPercent.toFixed(2)}% | Validation (${PERF_VALIDATION_PERCENT}%): ${
      validationPassed ? "PASS" : "FAIL"
    }`
  );
}

async function run() {
  const routeCases = await discoverRouteCases();
  if (!routeCases.length) {
    console.error("No API route handlers found under src/app/api/**/route.ts");
    process.exit(1);
  }

  console.log(`API smoke test started for ${routeCases.length} route handlers`);
  console.log(`Base URL: ${BASE_URL}`);
  console.log(`Mode: ${STRICT ? "strict (2xx/3xx only)" : "smoke (<500 is pass)"}`);
  if (PERF_COMPARE) {
    console.log("Benchmark: sequential vs concurrent");
  }
  console.log("");

  let passCount = 0;
  let failCount = 0;
  const skipCount = 0;

  for (const testCase of routeCases) {
    const result = await runSingleCase(testCase);
    const label = result.ok ? "PASS" : "FAIL";
    console.log(
      `${label} ${testCase.method.padEnd(6)} ${testCase.requestPath} -> ${result.message}`
    );
    if (result.ok) passCount += 1;
    else failCount += 1;
  }

  console.log("");
  console.log(`Passed: ${passCount}`);
  console.log(`Failed: ${failCount}`);
  console.log(`Skipped: ${skipCount}`);

  if (failCount === 0) {
    if (PERF_COMPARE) {
      console.log("");
      await runPerformanceComparison(routeCases);
    }
    console.log("Result: This is working and APIs are responding correctly.");
    process.exit(0);
  }

  console.log("Result: Some API checks failed. Please inspect the FAIL lines above.");
  process.exit(1);
}

run().catch((error) => {
  const message = error instanceof Error ? (error.stack ?? error.message) : String(error);
  console.error("Unexpected test runner error:");
  console.error(message);
  process.exit(1);
});
